version: "3.7"
services:

  server:
    container_name: server
    build: ./server
    ports:
      - "3001:3001"

  client:
    container_name: client
    build: ./client
    ports:
      - "3000:3000"
    stdin_open: true